{{- if .Values.clusterRoleBinding.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudflared.clusterRoleBindingName" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
  {{- with .Values.clusterRoleBinding.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
  name: {{ include "cloudflared.serviceAccountName" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "cloudflared.clusterRoleName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
