apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with (required "A valid .Values.cloudflared.certificate entry required!" .Values.cloudflared.certificate) }}
  cert.pem: {{ hasPrefix "e" . | ternary . (b64enc .) }}
  {{- end }}
  {{- with (required "A valid .Values.cloudflared.credentials entry required!" .Values.cloudflared.credentials) }}
  credentials.json: {{ hasPrefix "e" . | ternary . (b64enc .) }}
  {{- end }}
